imports:
- { resource: build.yml }
- { resource: services.yml }

parameters:
  application:
    name:         Course CLI added to Terminus
    slug:         courses-cli    # Used to name the built phar
    description:  "@todo add description"
  site: "beg-test"
